'use client'
import { Quote } from 'lucide-react';
import React from 'react'
import { Carousel, CarouselContent } from './ui/carousel';
import Autoplay from "embla-carousel-autoplay"

function Reviews() {
    return (
        <Carousel
            plugins={[Autoplay({ delay: 3000 })]}
            className='overflow-visible flex select-none'>
            <CarouselContent className='px-5'>
                <ReviewChip
                    description="No Gimmicks, just a solid all-rounder for gamers who want performance without compromise and style without flashiness. It's a fresh take on gaming audio aesthetics that doesn't scream “RGB Everything” - instead, it feels refined but still fun"
                    span="Generated by AI GPT"
                    tag1="Solid, high-performance,"
                    tag2="stylish gaming audio"
                />
                <ReviewChip
                    description="Easily the greatest headphones to ever launch on April 1st, 2025 globally. No bias. Just facts! P.S. Sales aren't live yet and I had to put something here… so yeah, I wrote this."
                    span="Armor Intern"
                    tag1="GOAT"
                    tag2="Headphones"
                />
                <ReviewChip
                    description="This magical headpiece is most wondrous! Sits on mine head like a king's crown, and the music soundeth like angels in mine ears. Truly a fine relic of modern craft. Would buy again, lest it be stolen by goblins."
                    span="knight"
                    tag1="A Most Wondrous"
                    tag2="Crown of Sound"
                />
            </CarouselContent>
        </Carousel>
    )
}

type ReviewChipProps = {
    description: string;
    tag1: string;
    tag2: string;
    span: string
    className?: string;
};

function ReviewChip({ description, span, tag1, tag2, className }: ReviewChipProps) {
    return (
        <div className={`p-8 my-5 mx-3 min-w-[90vw] md:min-w-[400px] z-10 border-2 border-black rounded-lg relative flex flex-col gap-10 justify-between overflow-visible ${className}`}>
            <Quote
                fill='black'
                stroke='0'
                className='rotate-180 z-1 size-20 absolute inset-0 inset-x-5 -inset-y-[35px]'
            />

            <div className='flex flex-col justify-between h-full'>
                <div>
                    <p className='pt-3 font-extralight text-border text-lg'>{description}</p>
                </div>
                <div className='mt-14'>
                    <p className='text-3xl'>{tag1} <span className='text-accent'>{tag2}</span></p>
                    <div className='mt-6 w-full h-1 border-b border-black' />
                </div>
            </div>
            <div>
                <p className='font-medium'>{span}</p>
            </div>
        </div>
    );
}

export default Reviews
